#ifndef DEFAULT_MAVLINK_BRIDGE_APP_INTERNAL_CFG_VALUES_H
#define DEFAULT_MAVLINK_BRIDGE_APP_INTERNAL_CFG_VALUES_H

#define MAVLINK_BRIDGE_APP_RECONNECT_INTERVAL_MS 1000
#define MAVLINK_BRIDGE_APP_STALE_TIMEOUT_MS      1000
#define MAVLINK_BRIDGE_APP_HEARTBEAT_INTERVAL_MS 1000
#define MAVLINK_BRIDGE_APP_STREAM_REQUEST_RETRY_MS 2000
#define MAVLINK_BRIDGE_APP_TARGET_DISCOVERY_TIMEOUT_MS 10000
#define MAVLINK_BRIDGE_APP_STREAM_REACQUIRE_TIMEOUT_MS 5000

#define MAVLINK_BRIDGE_APP_ATTITUDE_INTERVAL_US            200000
#define MAVLINK_BRIDGE_APP_LOCAL_POSITION_INTERVAL_US      200000
#define MAVLINK_BRIDGE_APP_GLOBAL_POSITION_INTERVAL_US     200000
#define MAVLINK_BRIDGE_APP_GPS_RAW_INTERVAL_US             500000
#define MAVLINK_BRIDGE_APP_EKF_STATUS_INTERVAL_US          500000

#endif
