#ifndef DEFAULT_MAVLINK_BRIDGE_APP_INTERNAL_CFG_VALUES_H
#define DEFAULT_MAVLINK_BRIDGE_APP_INTERNAL_CFG_VALUES_H

#define MAVLINK_BRIDGE_APP_RECONNECT_INTERVAL_MS 1000
#define MAVLINK_BRIDGE_APP_STALE_TIMEOUT_MS      1000
#define MAVLINK_BRIDGE_APP_HEARTBEAT_INTERVAL_MS 1000
#define MAVLINK_BRIDGE_APP_STREAM_REQUEST_RETRY_MS 2000
#define MAVLINK_BRIDGE_APP_TARGET_DISCOVERY_TIMEOUT_MS 10000
#define MAVLINK_BRIDGE_APP_STREAM_REACQUIRE_TIMEOUT_MS 5000

#define MAVLINK_BRIDGE_APP_ATTITUDE_INTERVAL_US            200000
#define MAVLINK_BRIDGE_APP_LOCAL_POSITION_INTERVAL_US      200000
#define MAVLINK_BRIDGE_APP_GLOBAL_POSITION_INTERVAL_US     200000
#define MAVLINK_BRIDGE_APP_GPS_RAW_INTERVAL_US             500000
#define MAVLINK_BRIDGE_APP_EKF_STATUS_INTERVAL_US          500000
#define MAVLINK_BRIDGE_APP_SYS_TIME_INTERVAL_US            1000000

/* CONFIG 이중버퍼 관련 */
#define MAVLINK_BRIDGE_APP_CONFIG_VERSION   1U
#define MAVLINK_BRIDGE_APP_CONFIG_SCOPE     2U
/* 인터벌 파라미터 범위: 10ms ~ 10s (us 단위: 10000 ~ 10000000) */
#define MAVLINK_BRIDGE_APP_PARAM_INTERVAL_MIN_US  10000U
#define MAVLINK_BRIDGE_APP_PARAM_INTERVAL_MAX_US  10000000U
/* ms 단위 파라미터 범위: 100ms ~ 60s */
#define MAVLINK_BRIDGE_APP_PARAM_MS_MIN  100U
#define MAVLINK_BRIDGE_APP_PARAM_MS_MAX  60000U

#endif
