#ifndef DEFAULT_LORA_FC_DOWNLINK_APP_MISSION_CFG_H
#define DEFAULT_LORA_FC_DOWNLINK_APP_MISSION_CFG_H

#include "lora_fc_downlink_app_interface_cfg.h"

#define LORA_FC_DOWNLINK_APP_DEFAULT_PERIOD_MS         1000
#define LORA_FC_DOWNLINK_APP_FC_STATE_PACKET_TYPE      1
#define LORA_FC_DOWNLINK_APP_SYSTEM_HEALTH_PACKET_TYPE 2
#define LORA_FC_DOWNLINK_APP_GPS_PACKET_TYPE           3

#define LORA_FC_DOWNLINK_APP_LORA_SERIAL_PATH \
    "/dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001-if00-port0"
#define LORA_FC_DOWNLINK_APP_LORA_BAUDRATE 57600

#endif
