#ifndef DEFAULT_LORA_FC_DOWNLINK_APP_TOPICID_VALUES_H
#define DEFAULT_LORA_FC_DOWNLINK_APP_TOPICID_VALUES_H

#define LORA_FC_DOWNLINK_APP_MISSION_TIDVAL(x) DEFAULT_LORA_FC_DOWNLINK_APP_MISSION_##x##_TOPICID

#define DEFAULT_LORA_FC_DOWNLINK_APP_MISSION_CMD_TOPICID     0x0C20
#define DEFAULT_LORA_FC_DOWNLINK_APP_MISSION_SEND_HK_TOPICID 0x0C21
#define DEFAULT_LORA_FC_DOWNLINK_APP_MISSION_HK_TLM_TOPICID  0x0C22

#define LORA_FC_DOWNLINK_APP_SYSTEM_HEALTH_MID_VALUE 0x1904
#define LORA_FC_DOWNLINK_APP_FC_EKF_LOCAL_STATE_MID_VALUE 0x1905
#define LORA_FC_DOWNLINK_APP_FC_ATTITUDE_STATE_MID_VALUE 0x1906
#define LORA_FC_DOWNLINK_APP_FC_GPS_RAW_STATE_MID_VALUE 0x1907
#define LORA_FC_DOWNLINK_APP_FC_EKF_STATUS_MID_VALUE 0x1908

/* Raw ground uplink frame forwarded over SB to uplink_app.
 * lora_fc_downlink_app가 LoRa RX 윈도우에서 읽은 "UP,..." 원문을 publish.
 * 값은 uplink_app의 UPLINK_APP_LORA_RAW_MID_VALUE와 반드시 동일해야 함. */
#define LORA_FC_DOWNLINK_APP_UPLINK_RAW_MID_VALUE 0x1909

#endif
