#ifndef DEFAULT_LORA_TDM_APP_MSGIDS_H
#define DEFAULT_LORA_TDM_APP_MSGIDS_H

#include "lora_tdm_app_msgid_values.h"

#define LORA_TDM_APP_CMD_MID          LORA_TDM_APP_CMD_PLATFORM_MIDVAL(CMD)
#define LORA_TDM_APP_SEND_HK_MID      LORA_TDM_APP_CMD_PLATFORM_MIDVAL(SEND_HK)
#define LORA_TDM_APP_HK_TLM_MID       LORA_TDM_APP_TLM_PLATFORM_MIDVAL(HK_TLM)
#define LORA_TDM_APP_LINK_STATUS_MID   LORA_TDM_APP_TLM_PLATFORM_MIDVAL(LINK_STATUS)

#endif
