#ifndef UPLINK_APP_EVENTIDS_H
#define UPLINK_APP_EVENTIDS_H

#define UPLINK_APP_STARTUP_EID      1
#define UPLINK_APP_COMMAND_ERR_EID  2
#define UPLINK_APP_NOOP_EID         3
#define UPLINK_APP_RESET_EID        4
#define UPLINK_APP_PUBLISH_EID      5
#define UPLINK_APP_STATE_BLOCK_EID  6
#define UPLINK_APP_AUTHZ_BLOCK_EID  7
#define UPLINK_APP_DUPLICATE_EID    8
#define UPLINK_APP_STATE_CORRUPT_EID 9

#endif

