#ifndef DEFAULT_CFS_CORE_APP_INTERFACE_CFG_VALUES_H
#define DEFAULT_CFS_CORE_APP_INTERFACE_CFG_VALUES_H

#define CFS_CORE_APP_CMD_MID_VALUE      0x18C0
#define CFS_CORE_APP_SEND_HK_MID_VALUE  0x18C1

#endif

