#ifndef DEFAULT_CFS_CORE_APP_INTERNAL_CFG_VALUES_H
#define DEFAULT_CFS_CORE_APP_INTERNAL_CFG_VALUES_H

#define CFS_CORE_APP_PLATFORM_PIPE_DEPTH  16
#define CFS_CORE_APP_PLATFORM_PIPE_NAME   "CFS_CORE_CMD"
#define CFS_CORE_APP_SB_POLL_TIMEOUT_MS   200
#define CFS_CORE_APP_PROTOTYPE_PERIOD_MS  1000
#define CFS_CORE_APP_ATTITUDE_TIMEOUT_MS  2000
#define CFS_CORE_APP_LOCAL_TIMEOUT_MS     2000
#define CFS_CORE_APP_GPS_TIMEOUT_MS       3000
#define CFS_CORE_APP_EKF_TIMEOUT_MS       2000
#define CFS_CORE_APP_BRIDGE_TIMEOUT_MS    3000
#define CFS_CORE_APP_NOMINAL_STABILITY_MS 10000

#endif

