#ifndef DEFAULT_CFS_CORE_APP_TOPICID_VALUES_H
#define DEFAULT_CFS_CORE_APP_TOPICID_VALUES_H

#define CFS_CORE_APP_BRIDGE_HK_MID_VALUE       0x08A0
#define CFS_CORE_APP_FC_EKF_LOCAL_STATE_MID_VALUE 0x1905
#define CFS_CORE_APP_FC_ATTITUDE_STATE_MID_VALUE  0x1906
#define CFS_CORE_APP_FC_GPS_RAW_STATE_MID_VALUE   0x1907
#define CFS_CORE_APP_FC_EKF_STATUS_MID_VALUE      0x1908

#endif

