#ifndef DEFAULT_CFS_CORE_APP_MISSION_CFG_H
#define DEFAULT_CFS_CORE_APP_MISSION_CFG_H

#define CFS_CORE_APP_IMAGE_ID_LEN     32
#define CFS_CORE_APP_CAMERA_ID_LEN    16
#define CFS_CORE_APP_ARTIFACT_REF_LEN 128

#endif

