#ifndef DEFAULT_CFS_CORE_APP_MSGDEFS_H
#define DEFAULT_CFS_CORE_APP_MSGDEFS_H

typedef enum
{
    CFS_CORE_APP_HEALTH_NOMINAL  = 0,
    CFS_CORE_APP_HEALTH_DEGRADED = 1,
    CFS_CORE_APP_HEALTH_RECOVERY = 2,
    CFS_CORE_APP_HEALTH_FAILED   = 3
} CFS_CORE_APP_HealthState_t;

typedef enum
{
    CFS_CORE_APP_FAULT_NONE           = 0,
    CFS_CORE_APP_FAULT_BRIDGE_TIMEOUT = 1,
    CFS_CORE_APP_FAULT_GPS_STALE      = 2,
    CFS_CORE_APP_FAULT_EKF_INVALID    = 3
} CFS_CORE_APP_FaultCode_t;

typedef enum
{
    CFS_CORE_APP_ROUTE_SEGMENT_NONE              = 0,
    CFS_CORE_APP_ROUTE_SEGMENT_MISSION_EXTENSION = 1,
    CFS_CORE_APP_ROUTE_SEGMENT_LANDING           = 2
} CFS_CORE_APP_RouteSegmentType_t;

#endif

