#ifndef DEFAULT_LORA_TDM_APP_TOPICID_VALUES_H
#define DEFAULT_LORA_TDM_APP_TOPICID_VALUES_H

#define DEFAULT_LORA_TDM_APP_MISSION_CMD_TOPICID        0x0C30
#define DEFAULT_LORA_TDM_APP_MISSION_SEND_HK_TOPICID    0x0C31
#define DEFAULT_LORA_TDM_APP_MISSION_HK_TLM_TOPICID     0x0C32
#define DEFAULT_LORA_TDM_APP_MISSION_LINK_STATUS_TOPICID 0x0C33

/* External MID values referenced by this app */
#define LORA_TDM_APP_DIAGNOSTIC_CMD_MID_VALUE        0x1910
#define LORA_TDM_APP_SYSTEM_HEALTH_MID_VALUE         0x1904
#define LORA_TDM_APP_FC_EKF_LOCAL_STATE_MID_VALUE    0x1905
#define LORA_TDM_APP_FC_ATTITUDE_STATE_MID_VALUE     0x1906
#define LORA_TDM_APP_FC_GPS_RAW_STATE_MID_VALUE      0x1907
#define LORA_TDM_APP_FC_EKF_STATUS_MID_VALUE         0x1908
#define LORA_TDM_APP_FC_SYS_TIME_MID_VALUE           0x1909
#define LORA_TDM_APP_UPLINK_APP_CMD_MID_VALUE        0x18D0
#define LORA_TDM_APP_UPLINK_STATUS_MID_VALUE         0x190A
#define LORA_TDM_APP_CONFIG_CMD_MID_VALUE            0x190E
#define LORA_TDM_APP_EXEC_RESULT_MID_VALUE           0x1912 /* BL-08(2026-07-22): 대상앱→uplink_app 실행결과 회신 (공용) */
#define LORA_TDM_APP_ROUTE_SNAPSHOT_MID_VALUE         0x1913 /* waypoint readback(2026-07-23): cfs_core_app 발행 */

/* Own MID values */
#define LORA_TDM_APP_CMD_MID_VALUE                   0x18E0
#define LORA_TDM_APP_SEND_HK_MID_VALUE               0x18E1
#define LORA_TDM_APP_HK_TLM_MID_VALUE               0x08E0
#define LORA_TDM_APP_LINK_STATUS_MID_VALUE           0x1911

#endif
