#ifndef UPLINK_APP_VERSION_H
#define UPLINK_APP_VERSION_H

#define UPLINK_APP_MAJOR_VERSION 1
#define UPLINK_APP_MINOR_VERSION 0
#define UPLINK_APP_REVISION      0
#define UPLINK_APP_MISSION_REV   0

#endif

