/* THIS IS GENERATED CONTENT, DO NOT EDIT */

static const size_t CFE_CONFIG_PLATFORM_ES_MEM_BLOCK_SIZE_CONTENT[17] = {
  CFE_PLATFORM_ES_MAX_BLOCK_SIZE,
  CFE_PLATFORM_ES_MEM_BLOCK_SIZE_16,
  CFE_PLATFORM_ES_MEM_BLOCK_SIZE_15,
  CFE_PLATFORM_ES_MEM_BLOCK_SIZE_14,
  CFE_PLATFORM_ES_MEM_BLOCK_SIZE_13,
  CFE_PLATFORM_ES_MEM_BLOCK_SIZE_12,
  CFE_PLATFORM_ES_MEM_BLOCK_SIZE_11,
  CFE_PLATFORM_ES_MEM_BLOCK_SIZE_10,
  CFE_PLATFORM_ES_MEM_BLOCK_SIZE_09,
  CFE_PLATFORM_ES_MEM_BLOCK_SIZE_08,
  CFE_PLATFORM_ES_MEM_BLOCK_SIZE_07,
  CFE_PLATFORM_ES_MEM_BLOCK_SIZE_06,
  CFE_PLATFORM_ES_MEM_BLOCK_SIZE_05,
  CFE_PLATFORM_ES_MEM_BLOCK_SIZE_04,
  CFE_PLATFORM_ES_MEM_BLOCK_SIZE_03,
  CFE_PLATFORM_ES_MEM_BLOCK_SIZE_02,
  CFE_PLATFORM_ES_MEM_BLOCK_SIZE_01 
};

static const size_t CFE_CONFIG_PLATFORM_ES_CDS_MEM_BLOCK_SIZE_CONTENT[17] = {
  CFE_PLATFORM_ES_CDS_MAX_BLOCK_SIZE,
  CFE_PLATFORM_ES_CDS_MEM_BLOCK_SIZE_16,
  CFE_PLATFORM_ES_CDS_MEM_BLOCK_SIZE_15,
  CFE_PLATFORM_ES_CDS_MEM_BLOCK_SIZE_14,
  CFE_PLATFORM_ES_CDS_MEM_BLOCK_SIZE_13,
  CFE_PLATFORM_ES_CDS_MEM_BLOCK_SIZE_12,
  CFE_PLATFORM_ES_CDS_MEM_BLOCK_SIZE_11,
  CFE_PLATFORM_ES_CDS_MEM_BLOCK_SIZE_10,
  CFE_PLATFORM_ES_CDS_MEM_BLOCK_SIZE_09,
  CFE_PLATFORM_ES_CDS_MEM_BLOCK_SIZE_08,
  CFE_PLATFORM_ES_CDS_MEM_BLOCK_SIZE_07,
  CFE_PLATFORM_ES_CDS_MEM_BLOCK_SIZE_06,
  CFE_PLATFORM_ES_CDS_MEM_BLOCK_SIZE_05,
  CFE_PLATFORM_ES_CDS_MEM_BLOCK_SIZE_04,
  CFE_PLATFORM_ES_CDS_MEM_BLOCK_SIZE_03,
  CFE_PLATFORM_ES_CDS_MEM_BLOCK_SIZE_02,
  CFE_PLATFORM_ES_CDS_MEM_BLOCK_SIZE_01 
};

static const size_t CFE_CONFIG_PLATFORM_SB_MEM_BLOCK_SIZE_CONTENT[17] = {
  CFE_PLATFORM_SB_MAX_BLOCK_SIZE,
  CFE_PLATFORM_SB_MEM_BLOCK_SIZE_16,
  CFE_PLATFORM_SB_MEM_BLOCK_SIZE_15,
  CFE_PLATFORM_SB_MEM_BLOCK_SIZE_14,
  CFE_PLATFORM_SB_MEM_BLOCK_SIZE_13,
  CFE_PLATFORM_SB_MEM_BLOCK_SIZE_12,
  CFE_PLATFORM_SB_MEM_BLOCK_SIZE_11,
  CFE_PLATFORM_SB_MEM_BLOCK_SIZE_10,
  CFE_PLATFORM_SB_MEM_BLOCK_SIZE_09,
  CFE_PLATFORM_SB_MEM_BLOCK_SIZE_08,
  CFE_PLATFORM_SB_MEM_BLOCK_SIZE_07,
  CFE_PLATFORM_SB_MEM_BLOCK_SIZE_06,
  CFE_PLATFORM_SB_MEM_BLOCK_SIZE_05,
  CFE_PLATFORM_SB_MEM_BLOCK_SIZE_04,
  CFE_PLATFORM_SB_MEM_BLOCK_SIZE_03,
  CFE_PLATFORM_SB_MEM_BLOCK_SIZE_02,
  CFE_PLATFORM_SB_MEM_BLOCK_SIZE_01 
};

