#ifndef CFS_CORE_APP_VERSION_H
#define CFS_CORE_APP_VERSION_H

#define CFS_CORE_APP_MAJOR_VERSION 1
#define CFS_CORE_APP_MINOR_VERSION 0
#define CFS_CORE_APP_REVISION      0
#define CFS_CORE_APP_MISSION_REV   0

#endif

