#ifndef MAVLINK_BRIDGE_APP_EVENTIDS_H
#define MAVLINK_BRIDGE_APP_EVENTIDS_H

#define MAVLINK_BRIDGE_APP_STARTUP_EID     1
#define MAVLINK_BRIDGE_APP_COMMAND_ERR_EID 2
#define MAVLINK_BRIDGE_APP_NOOP_EID        3
#define MAVLINK_BRIDGE_APP_RESET_EID       4
#define MAVLINK_BRIDGE_APP_LINK_EID        5
#define MAVLINK_BRIDGE_APP_PARSE_EID       6
#define MAVLINK_BRIDGE_APP_STREAM_EID              7
#define MAVLINK_BRIDGE_APP_MISSION_UPLOAD_INF_EID    8
#define MAVLINK_BRIDGE_APP_MISSION_UPLOAD_ERR_EID    9
#define MAVLINK_BRIDGE_APP_MISSION_DOWNLOAD_INF_EID 10
#define MAVLINK_BRIDGE_APP_MISSION_DOWNLOAD_ERR_EID 11
#define MAVLINK_BRIDGE_APP_ARMED_WARN_EID           12
#define MAVLINK_BRIDGE_APP_NONFINITE_VALUE_ERR_EID  13
#define MAVLINK_BRIDGE_APP_STATE_SAVE_FAIL_EID      14 /* BL-41(2026-07-23): SaveState 실패 */
#define MAVLINK_BRIDGE_APP_STATE_CORRUPT_EID        15 /* BL-41(2026-07-23): 상태 파일 손상 → 기본값 폴백 */

#endif
