#ifndef DEFAULT_MAVLINK_BRIDGE_APP_MSGDEFS_H
#define DEFAULT_MAVLINK_BRIDGE_APP_MSGDEFS_H

typedef enum
{
    MAVLINK_BRIDGE_LINK_DISCONNECTED = 0,
    MAVLINK_BRIDGE_LINK_DEGRADED     = 1,
    MAVLINK_BRIDGE_LINK_CONNECTED    = 2
} MAVLINK_BRIDGE_APP_LinkState_t;

typedef enum
{
    MAVLINK_BRIDGE_ERROR_NONE = 0,
    MAVLINK_BRIDGE_ERROR_LINK_DOWN,
    MAVLINK_BRIDGE_ERROR_READ_TIMEOUT,
    MAVLINK_BRIDGE_ERROR_SERIAL_OPEN_FAIL,
    MAVLINK_BRIDGE_ERROR_PARSE_FAIL,
    MAVLINK_BRIDGE_ERROR_UNSUPPORTED_MSG,
    MAVLINK_BRIDGE_ERROR_STALE_DATA,
    MAVLINK_BRIDGE_ERROR_EKF_UNHEALTHY,
    MAVLINK_BRIDGE_ERROR_GPS_NO_FIX,
    MAVLINK_BRIDGE_ERROR_INVALID_VALUE,
    MAVLINK_BRIDGE_ERROR_TIMESTAMP_INVALID
} MAVLINK_BRIDGE_APP_ErrorCode_t;

typedef enum
{
    MAVLINK_BRIDGE_MISSION_UPLOAD_IDLE     = 0,
    MAVLINK_BRIDGE_MISSION_UPLOAD_CLEARING = 1,
    MAVLINK_BRIDGE_MISSION_UPLOAD_ACTIVE   = 2
} MAVLINK_BRIDGE_APP_MissionUploadState_t;

typedef enum
{
    MAVLINK_BRIDGE_MISSION_DOWNLOAD_IDLE       = 0,
    MAVLINK_BRIDGE_MISSION_DOWNLOAD_WAIT_COUNT = 1,
    MAVLINK_BRIDGE_MISSION_DOWNLOAD_WAIT_ITEM  = 2
} MAVLINK_BRIDGE_APP_MissionDownloadState_t;

#define MAVLINK_BRIDGE_UPLOAD_RESULT_NONE    0U
#define MAVLINK_BRIDGE_UPLOAD_RESULT_SUCCESS 1U
#define MAVLINK_BRIDGE_UPLOAD_RESULT_TIMEOUT 2U
#define MAVLINK_BRIDGE_UPLOAD_RESULT_NAK     3U

/* 런타임 구성 파라미터 ID (scope=2) */
typedef enum
{
    MAVLINK_BRIDGE_PARAM_ATTITUDE_INTERVAL_US       = 0,
    MAVLINK_BRIDGE_PARAM_LOCAL_POSITION_INTERVAL_US = 1,
    MAVLINK_BRIDGE_PARAM_GLOBAL_POSITION_INTERVAL_US= 2,
    MAVLINK_BRIDGE_PARAM_GPS_RAW_INTERVAL_US        = 3,
    MAVLINK_BRIDGE_PARAM_EKF_STATUS_INTERVAL_US     = 4,
    MAVLINK_BRIDGE_PARAM_RECONNECT_INTERVAL_MS      = 5,
    MAVLINK_BRIDGE_PARAM_HEARTBEAT_INTERVAL_MS      = 6,
    MAVLINK_BRIDGE_PARAM_COUNT                      = 7
} MAVLINK_BRIDGE_APP_ParamId_t;

typedef enum
{
    MAVLINK_BRIDGE_CONFIG_RESULT_OK           = 0,
    MAVLINK_BRIDGE_CONFIG_RESULT_BAD_SCOPE    = 1,
    MAVLINK_BRIDGE_CONFIG_RESULT_BAD_VERSION  = 2,
    MAVLINK_BRIDGE_CONFIG_RESULT_BAD_PARAM    = 3,
    MAVLINK_BRIDGE_CONFIG_RESULT_BAD_VALUE    = 4,
    MAVLINK_BRIDGE_CONFIG_RESULT_BAD_LENGTH   = 5,
    MAVLINK_BRIDGE_CONFIG_RESULT_BAD_CHECKSUM = 6
} MAVLINK_BRIDGE_APP_ConfigResult_t;

typedef enum
{
    MAVLINK_BRIDGE_CONFIG_PENDING_IDLE     = 0,
    MAVLINK_BRIDGE_CONFIG_PENDING_PENDING  = 1,
    MAVLINK_BRIDGE_CONFIG_PENDING_REJECTED = 2
} MAVLINK_BRIDGE_APP_ConfigPendingState_t;

typedef struct
{
    uint32 AttitudeIntervalUs;
    uint32 LocalPositionIntervalUs;
    uint32 GlobalPositionIntervalUs;
    uint32 GpsRawIntervalUs;
    uint32 EkfStatusIntervalUs;
    uint32 ReconnectIntervalMs;
    uint32 HeartbeatIntervalMs;
} MAVLINK_BRIDGE_APP_ConfigParams_t;

/* BL-41(2026-07-23): CONFIG 영속화 — cfs_core_app/uplink_app과 동일한
 * 매직+체크섬+ConfigVersion+원자적 rename 패턴 (이 앱은 상태파일 신규). */
typedef struct
{
    uint32                            Magic;
    uint8                             ConfigVersion;
    uint8                             Reserved[3];
    MAVLINK_BRIDGE_APP_ConfigParams_t ActiveConfig;
    uint32                            Checksum;
} MAVLINK_BRIDGE_APP_PersistentState_t;

#endif
