#ifndef CFS_CORE_APP_EVENTIDS_H
#define CFS_CORE_APP_EVENTIDS_H

#define CFS_CORE_APP_STARTUP_EID     1
#define CFS_CORE_APP_COMMAND_ERR_EID 2
#define CFS_CORE_APP_NOOP_EID        3
#define CFS_CORE_APP_RESET_EID       4
#define CFS_CORE_APP_PUBLISH_EID     5
#define CFS_CORE_APP_HK_EID                6
#define CFS_CORE_APP_HEALTH_TRANSITION_EID 7
#define CFS_CORE_APP_SEQ_ERR_EID           8
#define CFS_CORE_APP_TIMESTAMP_ERR_EID     9
#define CFS_CORE_APP_BRIDGE_RESTART_EID   10
#define CFS_CORE_APP_VIEWPOINT_EID        11
#define CFS_CORE_APP_SEQ_GAP_EID          12
#define CFS_CORE_APP_RECOVERY_CMD_EID     13
#define CFS_CORE_APP_MODE_CMD_EID         14

#endif

