#ifndef DEFAULT_UPLINK_APP_MISSION_CFG_H
#define DEFAULT_UPLINK_APP_MISSION_CFG_H

#define UPLINK_APP_IMAGE_ID_LEN     32
#define UPLINK_APP_CAMERA_ID_LEN    16
#define UPLINK_APP_ARTIFACT_REF_LEN 128

#endif

