#ifndef DEFAULT_UPLINK_APP_FCNCODE_VALUES_H
#define DEFAULT_UPLINK_APP_FCNCODE_VALUES_H

#define UPLINK_APP_NOOP_CC           0
#define UPLINK_APP_RESET_COUNTERS_CC 1
#define UPLINK_APP_PROCESS_UPLINK_CC 2

#endif

