#ifndef DEFAULT_UPLINK_APP_MISSION_CFG_H
#define DEFAULT_UPLINK_APP_MISSION_CFG_H

#define UPLINK_APP_IMAGE_ID_LEN     32
#define UPLINK_APP_CAMERA_ID_LEN    16
#define UPLINK_APP_ARTIFACT_REF_LEN 128

#define UPLINK_APP_ROUTE_MAX_WAYPOINTS        8
#define UPLINK_APP_ROUTE_ALTITUDE_MIN_M       2.0f
#define UPLINK_APP_ROUTE_ALTITUDE_MAX_M       8.0f
#define UPLINK_APP_ROUTE_MIN_SEGMENT_DIST_M   0.5f
#define UPLINK_APP_ROUTE_MAX_SEGMENT_DIST_M   20.0f
#define UPLINK_APP_ROUTE_FLYABLE_X_MIN_M     -50.0f
#define UPLINK_APP_ROUTE_FLYABLE_X_MAX_M      50.0f
#define UPLINK_APP_ROUTE_FLYABLE_Y_MIN_M     -50.0f
#define UPLINK_APP_ROUTE_FLYABLE_Y_MAX_M      50.0f
#define UPLINK_APP_ROUTE_NOFLY_ENABLE         0
#define UPLINK_APP_ROUTE_NOFLY_X_MIN_M       -5.0f
#define UPLINK_APP_ROUTE_NOFLY_X_MAX_M        5.0f
#define UPLINK_APP_ROUTE_NOFLY_Y_MIN_M       -5.0f
#define UPLINK_APP_ROUTE_NOFLY_Y_MAX_M        5.0f

#endif

