#ifndef DEFAULT_UPLINK_APP_MISSION_CFG_H
#define DEFAULT_UPLINK_APP_MISSION_CFG_H

#define UPLINK_APP_ROUTE_MAX_WAYPOINTS        16
#define UPLINK_APP_ROUTE_ALTITUDE_MIN_M       2.0f
#define UPLINK_APP_ROUTE_ALTITUDE_MAX_M       8.0f
#define UPLINK_APP_ROUTE_SEGMENT_DIST_M       2.0f
#define UPLINK_APP_ROUTE_SEGMENT_DIST_TOL_M   0.0001f
#define UPLINK_APP_ROUTE_FLYABLE_X_MIN_M     -50.0f
#define UPLINK_APP_ROUTE_FLYABLE_X_MAX_M      50.0f
#define UPLINK_APP_ROUTE_FLYABLE_Y_MIN_M     -50.0f
#define UPLINK_APP_ROUTE_FLYABLE_Y_MAX_M      50.0f
#define UPLINK_APP_ROUTE_NOFLY_ENABLE         0
#define UPLINK_APP_ROUTE_NOFLY_X_MIN_M       -5.0f
#define UPLINK_APP_ROUTE_NOFLY_X_MAX_M        5.0f
#define UPLINK_APP_ROUTE_NOFLY_Y_MIN_M       -5.0f
#define UPLINK_APP_ROUTE_NOFLY_Y_MAX_M        5.0f

#endif

