#ifndef DEFAULT_UPLINK_APP_INTERFACE_CFG_VALUES_H
#define DEFAULT_UPLINK_APP_INTERFACE_CFG_VALUES_H

#define UPLINK_APP_CMD_MID_VALUE      0x18D0
#define UPLINK_APP_SEND_HK_MID_VALUE  0x18D1

#endif

