#ifndef DEFAULT_UPLINK_APP_INTERNAL_CFG_VALUES_H
#define DEFAULT_UPLINK_APP_INTERNAL_CFG_VALUES_H

#define UPLINK_APP_PLATFORM_PIPE_DEPTH  16
#define UPLINK_APP_PLATFORM_PIPE_NAME   "UPLINK_CMD"
#define UPLINK_APP_SB_POLL_TIMEOUT_MS   200
#define UPLINK_APP_PROTOTYPE_PERIOD_MS  1000
#define UPLINK_APP_PROTOCOL_VERSION     1
#define UPLINK_APP_MAX_PAYLOAD_LENGTH   196
#define UPLINK_APP_STATE_FILE_PATH      "/cf/uplink_app_state.bin"
#define UPLINK_APP_LORA_SERIAL_PATH \
    "/dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001-if00-port0"
#define UPLINK_APP_LORA_BAUDRATE        57600

#endif

