#ifndef DEFAULT_UPLINK_APP_MSGDEFS_H
#define DEFAULT_UPLINK_APP_MSGDEFS_H

typedef enum
{
    UPLINK_APP_RESULT_NONE           = 0,
    UPLINK_APP_RESULT_ACCEPT         = 1,
    UPLINK_APP_RESULT_REJECT         = 2,
    UPLINK_APP_RESULT_ROUTED         = 3,
    UPLINK_APP_RESULT_FAILED         = 4,
    UPLINK_APP_RESULT_REJECT_VERSION = 5,
    UPLINK_APP_RESULT_REJECT_CLASS   = 6,
    UPLINK_APP_RESULT_REJECT_LENGTH  = 7,
    UPLINK_APP_RESULT_ROUTE_MISS     = 8,
    UPLINK_APP_RESULT_REJECT_ROUTE   = 9,
    UPLINK_APP_RESULT_REJECT_SEQUENCE = 10
} UPLINK_APP_Result_t;

typedef enum
{
    UPLINK_APP_LINK_NOMINAL  = 0,
    UPLINK_APP_LINK_DEGRADED = 1,
    UPLINK_APP_LINK_LOST     = 2,
    UPLINK_APP_LINK_FAILED   = 3
} UPLINK_APP_LinkState_t;

typedef enum
{
    UPLINK_APP_CLASS_NONE         = 0,
    UPLINK_APP_CLASS_CONFIG       = 1,
    UPLINK_APP_CLASS_ROUTE_UPDATE = 2,
    UPLINK_APP_CLASS_VIEWPOINT    = 3,
    UPLINK_APP_CLASS_RECOVERY     = 4,
    UPLINK_APP_CLASS_MODE         = 5,
    UPLINK_APP_CLASS_DIAGNOSTIC   = 6
} UPLINK_APP_CommandClass_t;

typedef enum
{
    UPLINK_APP_ROUTE_SEGMENT_NONE              = 0,
    UPLINK_APP_ROUTE_SEGMENT_MISSION_EXTENSION = 1,
    UPLINK_APP_ROUTE_SEGMENT_LANDING           = 2
} UPLINK_APP_RouteSegmentType_t;

typedef enum
{
    UPLINK_APP_ROUTE_NONE      = 0,
    UPLINK_APP_ROUTE_CORE      = 1,
    UPLINK_APP_ROUTE_DOWNLINK  = 2
} UPLINK_APP_RouteTarget_t;

typedef enum
{
    UPLINK_APP_CONFIG_IDLE       = 0,
    UPLINK_APP_CONFIG_PENDING    = 1,
    UPLINK_APP_CONFIG_VALIDATING = 2,
    UPLINK_APP_CONFIG_REJECTED   = 3
} UPLINK_APP_ConfigPendingState_t;

#endif

